jobs:
  check:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./test/check

name: Verify

on:
  schedule:
    - cron: "10 1/3 * * *"
